version: '3.0'
services:
  slash_worker:
    image: node:16.3-buster-slim

    environment:
      VS_ENV: 'dev'

    volumes:
      - './:/home/node'

    command: ['tail', '-f', '/dev/null']

    networks:
      - default
      - backend

networks:
  default:
    external:
      name: dexnetwork
  backend:
    external:
      name: dexnetworkbackend
